name: Sync to GitHub
on:
  schedule:
    - cron: '0 3 * * *'  # 每天凌晨3点执行
  push:  # 可选：本地推送时也触发同步
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Push to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          repository: github.com/mavyum/Knowledge  # 替换为你的GitHub仓库地址
          force: true
